language: php

sudo: false

php:
  - 7.0

before_install:
  - composer self-update

install:
  - composer install --prefer-dist --no-interaction --dev

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/php-cs-fixer fix -v --dry-run

after_success:
  - php vendor/bin/coveralls -v
